// <auto-generated />
using System;
using Mahamma.Identity.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mahamma.Identity.Api.Migrations
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20220121082258_AddSubTaskPermissionLocalization")]
    partial class AddSubTaskPermissionLocalization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mahamma.Identity.Domain.Language.Entity.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Alias");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DeletedStatus")
                        .HasColumnType("int")
                        .HasColumnName("DeletedStatus");

                    b.Property<bool>("IsRtl")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "En",
                            CreationDate = new DateTime(2021, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            IsRtl = false,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Alias = "Ar",
                            CreationDate = new DateTime(2021, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            IsRtl = true,
                            Name = "Arabic"
                        });
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Role.Entity.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DeletedStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Page");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            Name = "WorkspaceProfile"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            Name = "ProjectProfile"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            Name = "TaskProfile"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            Name = "SubtaskProfile"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            Name = "ManageRoles"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            Name = "MeetingProfile"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            Name = "ManageMeetings"
                        });
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Role.Entity.PageLocalization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DeletedStatus")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DisplayName");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("LanguageId");

                    b.Property<int>("PageId")
                        .HasColumnType("int")
                        .HasColumnName("PageId");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PageId");

                    b.ToTable("PageLocalization");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Workspace Profile",
                            LanguageId = 1,
                            PageId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "الصفحة الخاصة بمساحة العمل",
                            LanguageId = 2,
                            PageId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Project Profile",
                            LanguageId = 1,
                            PageId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "الصفحة الخاصة بالمشروع",
                            LanguageId = 2,
                            PageId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Task Profile",
                            LanguageId = 1,
                            PageId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "الصفحة الخاصة بالمهمة",
                            LanguageId = 2,
                            PageId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Subtask Profile",
                            LanguageId = 1,
                            PageId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "الصفحة الخاصة بالمهمة الفرعية",
                            LanguageId = 2,
                            PageId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Manage Roles",
                            LanguageId = 1,
                            PageId = 5
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Meeting Profile",
                            LanguageId = 1,
                            PageId = 7
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "الصفحة الخاصة بالاجتماعات",
                            LanguageId = 2,
                            PageId = 7
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Manage Meetings",
                            LanguageId = 1,
                            PageId = 8
                        });
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Role.Entity.PagePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DeletedStatus")
                        .HasColumnType("int");

                    b.Property<int>("PageId")
                        .HasColumnType("int")
                        .HasColumnName("PageId");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.HasIndex("PermissionId");

                    b.ToTable("PagePermission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 2,
                            PermissionId = 15
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 2,
                            PermissionId = 16
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 2,
                            PermissionId = 17
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 2,
                            PermissionId = 18
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 2,
                            PermissionId = 19
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 3,
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 3,
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 3,
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 3,
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 2,
                            PermissionId = 10
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 2,
                            PermissionId = 12
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 2,
                            PermissionId = 11
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 2,
                            PermissionId = 13
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 3,
                            PermissionId = 10
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 3,
                            PermissionId = 12
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 3,
                            PermissionId = 11
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 3,
                            PermissionId = 13
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 3,
                            PermissionId = 14
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 4,
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 4,
                            PermissionId = 5
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 4,
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 4,
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 4,
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 4,
                            PermissionId = 10
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 4,
                            PermissionId = 12
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 4,
                            PermissionId = 11
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 4,
                            PermissionId = 13
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 4,
                            PermissionId = 14
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 5,
                            PermissionId = 21
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 5,
                            PermissionId = 20
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 5,
                            PermissionId = 22
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 5,
                            PermissionId = 23
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 1,
                            PermissionId = 18
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 1,
                            PermissionId = 19
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 2,
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 1,
                            PermissionId = 16
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 3,
                            PermissionId = 28
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 8,
                            PermissionId = 30
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 8,
                            PermissionId = 31
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 8,
                            PermissionId = 32
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 8,
                            PermissionId = 33
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 8,
                            PermissionId = 34
                        },
                        new
                        {
                            Id = 54,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 8,
                            PermissionId = 36
                        },
                        new
                        {
                            Id = 63,
                            CreationDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            PageId = 8,
                            PermissionId = 41
                        });
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Role.Entity.PermissionLocalization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DeletedStatus")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DisplayName");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("LanguageId");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PermissionId");

                    b.ToTable("PermissionLocalization");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Add WorkSpace",
                            LanguageId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "اضافة مساحة عمل",
                            LanguageId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "View Workspace",
                            LanguageId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "مشاهدة  مساحة العمل",
                            LanguageId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Update Workspace",
                            LanguageId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "تعديل مساحة العمل",
                            LanguageId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Delete Workspace",
                            LanguageId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "مسح مساحة العمل",
                            LanguageId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "View Task",
                            LanguageId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "مشاهدة المهمة",
                            LanguageId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Add Task",
                            LanguageId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "اضافة مهمة",
                            LanguageId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Update Task",
                            LanguageId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "تعديل المهمة",
                            LanguageId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Delete Task",
                            LanguageId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "مسح المهمة",
                            LanguageId = 2,
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Archive Task",
                            LanguageId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "ارشيف المهمة",
                            LanguageId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Add File",
                            LanguageId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "اضافة ملفات",
                            LanguageId = 2,
                            PermissionId = 10
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "View File",
                            LanguageId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "مشاهدة ملف",
                            LanguageId = 2,
                            PermissionId = 11
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Delete File",
                            LanguageId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "مسح ملف",
                            LanguageId = 2,
                            PermissionId = 12
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Assign Member",
                            LanguageId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "اضافة عضو",
                            LanguageId = 2,
                            PermissionId = 13
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Add Comment",
                            LanguageId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "اضافة كومنت",
                            LanguageId = 2,
                            PermissionId = 14
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Add Project",
                            LanguageId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "اضافة مشروع",
                            LanguageId = 2,
                            PermissionId = 15
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "View Project",
                            LanguageId = 1,
                            PermissionId = 16
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "مشاهدة مشروع",
                            LanguageId = 2,
                            PermissionId = 16
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Update Project",
                            LanguageId = 1,
                            PermissionId = 17
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "تعديل مشروع",
                            LanguageId = 2,
                            PermissionId = 17
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Delete Project",
                            LanguageId = 1,
                            PermissionId = 18
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "مسح مشروع",
                            LanguageId = 2,
                            PermissionId = 18
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Archive Project",
                            LanguageId = 1,
                            PermissionId = 19
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "ارشيف المشروع",
                            LanguageId = 2,
                            PermissionId = 19
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "View Role",
                            LanguageId = 1,
                            PermissionId = 20
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "مشاهدة دور",
                            LanguageId = 2,
                            PermissionId = 20
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Add Role",
                            LanguageId = 1,
                            PermissionId = 21
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "اضافة دور",
                            LanguageId = 2,
                            PermissionId = 21
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Update Role",
                            LanguageId = 1,
                            PermissionId = 22
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "تعديل دور",
                            LanguageId = 2,
                            PermissionId = 22
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Delete Role",
                            LanguageId = 1,
                            PermissionId = 23
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Add Meeting General",
                            LanguageId = 1,
                            PermissionId = 30
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "اضافة اجتماع على العموم",
                            LanguageId = 2,
                            PermissionId = 30
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Add Meeting Workspace",
                            LanguageId = 1,
                            PermissionId = 31
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "اضافة اجتماع على مستوى مساحة العمل",
                            LanguageId = 2,
                            PermissionId = 31
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Add Meeting Project",
                            LanguageId = 1,
                            PermissionId = 32
                        },
                        new
                        {
                            Id = 54,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "اضافة اجتماع على مستوى المشروع",
                            LanguageId = 2,
                            PermissionId = 32
                        },
                        new
                        {
                            Id = 55,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Add Meeting Task",
                            LanguageId = 1,
                            PermissionId = 33
                        },
                        new
                        {
                            Id = 56,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "اضافة اجتماع على مستوى المهمة",
                            LanguageId = 2,
                            PermissionId = 33
                        },
                        new
                        {
                            Id = 57,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Update Meeting",
                            LanguageId = 1,
                            PermissionId = 34
                        },
                        new
                        {
                            Id = 58,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "تعديل الاجتماع",
                            LanguageId = 2,
                            PermissionId = 34
                        },
                        new
                        {
                            Id = 59,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Delete Meeting",
                            LanguageId = 1,
                            PermissionId = 35
                        },
                        new
                        {
                            Id = 61,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "View Meeting",
                            LanguageId = 1,
                            PermissionId = 36
                        },
                        new
                        {
                            Id = 62,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "مشاهدة الاجتماع",
                            LanguageId = 2,
                            PermissionId = 36
                        },
                        new
                        {
                            Id = 71,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Add Meeting",
                            LanguageId = 1,
                            PermissionId = 41
                        },
                        new
                        {
                            Id = 72,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "اضافة اجتماع",
                            LanguageId = 2,
                            PermissionId = 41
                        },
                        new
                        {
                            Id = 73,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "Add Sub Task",
                            LanguageId = 2,
                            PermissionId = 28
                        },
                        new
                        {
                            Id = 74,
                            CreationDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedStatus = 1,
                            DisplayName = "اضافة مهمة فرعية",
                            LanguageId = 2,
                            PermissionId = 28
                        });
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Role.Entity.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyId");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DeletedStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName", "CompanyId")
                        .IsUnique()
                        .HasDatabaseName("CompanyRoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL AND [CompanyId] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Role.Entity.RolePagePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DeletedStatus")
                        .HasColumnType("int");

                    b.Property<int>("PagePermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PagePermissionId");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("PagePermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePagePermission");
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Role.Enum.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AddWorkspace"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ViewWorkspace"
                        },
                        new
                        {
                            Id = 3,
                            Name = "UpdateWorkspace"
                        },
                        new
                        {
                            Id = 4,
                            Name = "DeleteWorkspace"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ViewTask"
                        },
                        new
                        {
                            Id = 6,
                            Name = "AddTask"
                        },
                        new
                        {
                            Id = 7,
                            Name = "UpdateTask"
                        },
                        new
                        {
                            Id = 8,
                            Name = "DeleteTask"
                        },
                        new
                        {
                            Id = 9,
                            Name = "ArchiveTask"
                        },
                        new
                        {
                            Id = 10,
                            Name = "AddFile"
                        },
                        new
                        {
                            Id = 11,
                            Name = "ViewFile"
                        },
                        new
                        {
                            Id = 12,
                            Name = "DeleteFile"
                        },
                        new
                        {
                            Id = 13,
                            Name = "AssignMember"
                        },
                        new
                        {
                            Id = 14,
                            Name = "AddComment"
                        },
                        new
                        {
                            Id = 15,
                            Name = "AddProject"
                        },
                        new
                        {
                            Id = 16,
                            Name = "ViewProject"
                        },
                        new
                        {
                            Id = 17,
                            Name = "UpdateProject"
                        },
                        new
                        {
                            Id = 18,
                            Name = "DeleteProject"
                        },
                        new
                        {
                            Id = 19,
                            Name = "ArchiveProject"
                        },
                        new
                        {
                            Id = 20,
                            Name = "ViewRole"
                        },
                        new
                        {
                            Id = 21,
                            Name = "AddRole"
                        },
                        new
                        {
                            Id = 22,
                            Name = "UpdateRole"
                        },
                        new
                        {
                            Id = 23,
                            Name = "DeleteRole"
                        },
                        new
                        {
                            Id = 24,
                            Name = "UploadDocument"
                        },
                        new
                        {
                            Id = 25,
                            Name = "DownloadDocument"
                        },
                        new
                        {
                            Id = 26,
                            Name = "DeleteDocument"
                        },
                        new
                        {
                            Id = 27,
                            Name = "SubmitTask"
                        },
                        new
                        {
                            Id = 28,
                            Name = "AddSubTask"
                        },
                        new
                        {
                            Id = 30,
                            Name = "AddMeetingGeneral"
                        },
                        new
                        {
                            Id = 31,
                            Name = "AddMeetingWorkspace"
                        },
                        new
                        {
                            Id = 32,
                            Name = "AddMeetingProject"
                        },
                        new
                        {
                            Id = 33,
                            Name = "AddMeetingTask"
                        },
                        new
                        {
                            Id = 34,
                            Name = "UpdateMeeting"
                        },
                        new
                        {
                            Id = 36,
                            Name = "ViewMeeting"
                        },
                        new
                        {
                            Id = 41,
                            Name = "AddMeeting"
                        });
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.User.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Bio");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyId");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DeletedStatus")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullName");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JobTitle");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("LanguageId");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProfileImage");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Skills");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserProfileStatusId")
                        .HasColumnType("int")
                        .HasColumnName("UserProfileStatusId");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("int")
                        .HasColumnName("WorkingDays");

                    b.Property<int>("WorkingHours")
                        .HasColumnType("int")
                        .HasColumnName("WorkingHours");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.UserRole.Entity.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DeletedStatus")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Role.Entity.PageLocalization", b =>
                {
                    b.HasOne("Mahamma.Identity.Domain.Language.Entity.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mahamma.Identity.Domain.Role.Entity.Page", null)
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Role.Entity.PagePermission", b =>
                {
                    b.HasOne("Mahamma.Identity.Domain.Role.Entity.Page", "Page")
                        .WithMany("PagePermissions")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mahamma.Identity.Domain.Role.Enum.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Role.Entity.PermissionLocalization", b =>
                {
                    b.HasOne("Mahamma.Identity.Domain.Language.Entity.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mahamma.Identity.Domain.Role.Enum.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Role.Entity.RolePagePermission", b =>
                {
                    b.HasOne("Mahamma.Identity.Domain.Role.Entity.PagePermission", "PagePermission")
                        .WithMany("RolePagePermissions")
                        .HasForeignKey("PagePermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mahamma.Identity.Domain.Role.Entity.Role", null)
                        .WithMany("RolePagePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PagePermission");
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.User.Entity.User", b =>
                {
                    b.HasOne("Mahamma.Identity.Domain.Language.Entity.Language", null)
                        .WithMany("UserList")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.UserRole.Entity.UserRole", b =>
                {
                    b.HasOne("Mahamma.Identity.Domain.Role.Entity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mahamma.Identity.Domain.User.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Mahamma.Identity.Domain.Role.Entity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Mahamma.Identity.Domain.User.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Mahamma.Identity.Domain.User.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Mahamma.Identity.Domain.User.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Language.Entity.Language", b =>
                {
                    b.Navigation("UserList");
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Role.Entity.Page", b =>
                {
                    b.Navigation("PagePermissions");
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Role.Entity.PagePermission", b =>
                {
                    b.Navigation("RolePagePermissions");
                });

            modelBuilder.Entity("Mahamma.Identity.Domain.Role.Entity.Role", b =>
                {
                    b.Navigation("RolePagePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
